---
title: "Data visualization HW1 - New York Times Plot | Ukrainian Catholic University | 2019"
author: "Eduard Kovalchuk"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Load libraries
```{r}
suppressMessages(library(ggplot2))
suppressMessages(library(purrr))
suppressMessages(library(dplyr))
```
Helper functions
```{r}

format_double <- function(x) {
  if (x == 0) {
    "0.0"
  } else if (x > 0) {
    paste("+", x, sep="")
  } else {
    paste(x, sep="")
  }
}

```

Load data
```{r}
data <- read.csv("GLB.Ts+dSST.csv", skip = 1)
data$AnualAvg = data %>% select(2:13) %>% rowMeans()

years_by_10 <- seq(min(data$Year), max(data$Year), 10)
temp_by_02 <- seq(min(data$AnualAvg) , max(data$AnualAvg), 0.2) %>%
                map(round, digits = 1) %>%
                map(function(x) {x+0.1}) %>%
                map(format_double)
temp_by_02 <- unlist(temp_by_02)

data
```

```{r}
ggplot(data, aes(Year, AnualAvg)) + 
  geom_vline(xintercept = c(1880, 1910, 1940, 1970, 2000), colour="white") +
  geom_hline(yintercept = 0, color = "gray65") +
  geom_vline(xintercept = c(2022), colour="white", size = 15) +
  geom_point(colour = "gray40", fill = "#F26C08", pch=21, size=2, stroke = 0.6) + 
  theme_light() + 
  theme(panel.border = element_blank(),
        axis.text = element_text(colour = "gray70", size=8),
        panel.grid = element_line(colour="gray90"),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_text(hjust = -0.02, colour = "gray70", size=7, margin = margin(15,0,0,0))) +
  scale_x_continuous(name="Source: NASA", labels = years_by_10, breaks = years_by_10, expand=c(0.01, 1)) +
  scale_y_continuous(labels = temp_by_02, breaks = as.numeric(temp_by_02), limits = c(-0.6, 1)) +
  annotate("label", x = 1904.6, y = 0.99,  label = strrep(" ", 27), size=8, colour="white", fontface=2) +
  annotate("label", x = 1888, y = 0.83,  label = "ALL YEARS", size=3, colour="white", fill="#F26C08") +
  annotate("label", x = 1908.5, y = 0.83,  label = "WITHOUT EL NIÑO", size=2.7, colour="gray60", fill="gray90") +
  annotate("text", x = 1900.5, y = -0.49, label = "1904", size=3, colour="gray15") +
  annotate("text", x = 1948, y = 0.21, label = "1944", size=3, colour="gray15") +
  annotate("text", x = 1994, y = 0.625, label = "1998", size=3, colour="gray15") +
  annotate("text", x = 2018, y = 0.73, label = "2014", size=3, colour="gray15") +
  annotate("text", x = 2019, y = 0.85, label = "2015", size=3, colour="gray15") + 
  annotate("text", x = 2021, y = 0.9, label = "2017", size=3, colour="gray15") + 
  annotate("text", x = 2020, y = 0.99, label = "2016", size=3, colour="gray15", fontface=2) +
  annotate("text",
           x = 1904,
           y = 0.99,
           label = "Annual Global Surface Temperature,    \nRelative to Late 19th Century Average",
           size=3.1,
           colour="gray15",
           fontface=2) +
  annotate("text",
           x = 2009.5,
           y = 0.035,
           label = "    HOTTER THAN THE\n1880-1899 AVERAGE\n\n                        COLDER",
           size=2.3,
           colour="gray15")
  

```

